### ISSUE TITLE
Import fail

### ISSUE THREAD

**Issue by YacratesWyh** [jesenzhang/ComfyUI_StreamDiffusion#3]
[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "/home/admin188/AI/webui/ComfyUI/server.py", line 633, in trigger_on_prompt
    json_data = handler(json_data)
  File "/home/admin188/AI/webui/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 821, in prompt_handler
    if node["class_type"] == "smZ CLIPTextEncode":
KeyError: 'class_type'
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/admin188/AI/webui/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/home/admin188/AI/webui/ComfyUI/server.py", line 472, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "/home/admin188/AI/webui/ComfyUI/execution.py", line 600, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'class_type'

**Comment by YacratesWyh** [comment]
After uninstall smZnodes, still have the following problem:
FETCH DATA from: /home/admin188/AI/webui/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
data_path:  /home/admin188/AI/webui/ComfyUI/custom_nodes/comfyui-mixlab-nodes/data
got prompt
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/admin188/AI/webui/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/home/admin188/AI/webui/ComfyUI/server.py", line 472, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "/home/admin188/AI/webui/ComfyUI/execution.py", line 600, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'class_type'

**Comment by YacratesWyh** [comment]
So what's the dependencies? The error is classtype not found, not a web error.

**Comment by YacratesWyh** [comment]
Problem fixed by update diffusers version, you should mention such dependence as the ComfyUI does not require such install.

**Comment by rttt1093** [comment]
I've resolved this problem with `pip install diffusers==0.25.0` on my environment.
