### ISSUE TITLE
Migrate from diffuser pipeline to comfyui env?

### ISSUE THREAD

**Issue by YacratesWyh** [jesenzhang/ComfyUI_StreamDiffusion#4]
I think the loader is not loading models correctly from /models/vae and checkpoints.
<img width="321" alt="image" src="https://github.com/jesenzhang/ComfyUI_StreamDiffusion/assets/8447769/e0397e81-af5b-47ef-8594-2070128da90e">

ERROR:root:Traceback (most recent call last):
  File "/home/admin188/AI/webui/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/admin188/AI/webui/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/admin188/AI/webui/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin188/AI/webui/ComfyUI/custom_nodes/ComfyUI_StreamDiffusion/nodes.py", line 232, in sample
    output = model.sample(image).permute(0, 2, 3, 1)
  File "/home/admin188/AI/webui/ComfyUI/custom_nodes/ComfyUI_StreamDiffusion/streamdiffusion/wrapper.py", line 330, in sample
    self.stream.sample(image)
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin188/AI/webui/ComfyUI/custom_nodes/ComfyUI_StreamDiffusion/streamdiffusion/pipeline.py", line 540, in sample
    x_0_pred_out = self.predict_x0_batch(x_t_latent)
  File "/home/admin188/AI/webui/ComfyUI/custom_nodes/ComfyUI_StreamDiffusion/streamdiffusion/pipeline.py", line 443, in predict_x0_batch
    x_0_pred_batch, model_pred = self.unet_step(x_t_latent, t_list)
  File "/home/admin188/AI/webui/ComfyUI/custom_nodes/ComfyUI_StreamDiffusion/streamdiffusion/pipeline.py", line 356, in unet_step
    model_pred = self.unet(
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 960, in forward
    timesteps = timesteps.expand(sample.shape[0])
RuntimeError: The expanded size of the tensor (202) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [202].  Tensor sizes: [4]

**Comment by jesenzhang** [comment]
I just used the streamdifussion's function, I tried some checkpoints and loras , it worked even through some parameters could not be loaded. Migrating from diffuser pipeline to comfyui env is worthwhile, there is another crate https://github.com/Limitex/ComfyUI-Diffusers , it is a program that allows you to use Huggingface Diffusers module with ComfyUI  and maybe is the better way.
